name: Books list workflow
on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:
permissions:
  contents: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: marcobacis/goodreads-scrape-action@v0.1.1
        with:
          user: 22830084
          shelf: currently-reading
          output_path: data/books.json

      - name: Commit books list file back to the repo
        shell: bash
        run: |
          git config --global user.email "actions@users.noreply.github.com"
          git config --global user.name "goodreads bot"
          git diff --quiet || (git add data/books.json && git commit -m "Updated books list from goodreads")
          git push