name: Books list workflow
on:
  schedule: # Run workflow automatically
    - cron: '0 0 * * *' # Runs every day at midnight
  workflow_dispatch: # Run workflow manually (without waiting for the cron to be called), through the GitHub Actions Workflow page directly
permissions:
  contents: write # To write the generated contents

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'
          cache: 'pip'
      
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r books_scraper/requirements.txt

      - name: Update current books list json file
        run: python books_scraper/scrape_books.py data/books.json

      - name: Commit books list file back to the repo
        shell: bash
        run: |
          git config --global user.email "actions@users.noreply.github.com"
          git config --global user.name "goodreads bot"
          git diff --quiet || (git add data/books.json && git commit -m "Updated books list from goodreads")
          git push